/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.ecnantes.PGMApp;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        //test diff 
        /*Integer[][] tableau = new Integer[2][3];
        for (int i = 0;i < tableau.length; i++) {
         for (int j = 0;j < tableau[i].length;j++) {
            tableau[i][j] = i + j;
            System.out.print(tableau[i][j] + " ");
         }
         System.out.println();
        }
        System.out.println();
       
        
        PGMImage test = new PGMImage("cc", 2, 3, tableau); 
        Integer[][] tableau2 = new Integer[2][3];
        for (int i = 0;i < tableau2.length; i++) {
         for (int j = 0;j < tableau2[i].length;j++) {
            tableau2[i][j] = i + j;
            
         }
         System.out.println();
        }
        System.out.println();
        
        tableau2[0][0]=1; 
        for (int i = 0;i < tableau2.length; i++) {
         for (int j = 0;j < tableau2[i].length;j++) {
           
            System.out.print(tableau2[i][j] + " ");
         }
         System.out.println();
        }
        System.out.println();
        
        PGMImage test2 = new PGMImage("cc2", 2, 3, tableau2); 
        
        PGMImage res =test.difference(test2); 
        Integer[][] tableaudiff = res.getContent(); 
        for (int i2 = 0;i2 < tableaudiff.length; i2++) {
         for (int j2 = 0;j2 < tableaudiff[i2].length;j2++) {
            
            System.out.print(tableaudiff[i2][j2] + " ");
         }
         System.out.println();
        }
        System.out.println();
        */
        
        //test threshold
        /*Integer[][] tableau = new Integer[2][3];
        for (int i = 0;i < tableau.length; i++) {
         for (int j = 0;j < tableau[i].length;j++) {
            tableau[i][j] = i + j;
            System.out.print(tableau[i][j] + " ");
         }
         System.out.println();
        }
        System.out.println();
        PGMImage test = new PGMImage("cc", 2, 3, tableau); 
        PGMImage res =test.thresholding(2); 
        
        Integer[][] tableauthres = res.getContent(); 
        for (int i2 = 0;i2 < tableauthres.length; i2++) {
         for (int j2 = 0;j2 < tableauthres[i2].length;j2++) {
            
            System.out.print(tableauthres[i2][j2] + " ");
         }
         System.out.println();
        }
        System.out.println();
        */
        
        //test enlargement 
        /*Integer[][] tableau = new Integer[2][3];
        for (int i = 0;i < tableau.length; i++) {
         for (int j = 0;j < tableau[i].length;j++) {
            tableau[i][j] = i + j;
            System.out.print(tableau[i][j] + " ");
         }
         System.out.println();
        }
        System.out.println();
        PGMImage test = new PGMImage("cc", 2, 3, tableau); 
        PGMImage res =test.enlargement(2); 
        
        Integer[][] tableauthres = res.getContent(); 
        for (int i2 = 0;i2 < tableauthres.length; i2++) {
         for (int j2 = 0;j2 < tableauthres[i2].length;j2++) {
            
            System.out.print(tableauthres[i2][j2] + " ");
         }
         System.out.println();
        }
        System.out.println();
        
        }*/
        
        
        //test reduction 
        Integer[][] tableau = new Integer[4][7];
        for (int i = 0;i < tableau.length; i++) {
         for (int j = 0;j < tableau[i].length;j++) {
            tableau[i][j] = i + j;
            System.out.print(tableau[i][j] + " ");
         }
         System.out.println();
        }
        System.out.println();
        PGMImage test = new PGMImage("cc", 4, 7, tableau); 
        PGMImage res =test.reduction(0); 
        
        Integer[][] tableauthres = res.getContent(); 
        for (int i2 = 0;i2 < tableauthres.length; i2++) {
            for (int j2 = 0;j2 < tableauthres[i2].length;j2++) {

               System.out.print(tableauthres[i2][j2] + " ");
            }
            System.out.println();
        }
        System.out.println();
        
        }
        
}
